title: トークリハ
description: AIと安心して会話練習できるiOSアプリ
theme: jekyll-theme-minimal
baseurl: "/talkrehearsal-legal"
url: "https://yuki7827.github.io"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
